services:
  # Database
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: onetrade-postgres
    environment:
      POSTGRES_DB: onetrade
      POSTGRES_USER: onetrade
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-onetrade_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onetrade"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache
  redis:
    image: redis:7-alpine
    container_name: onetrade-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Message Queue
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: onetrade-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: onetrade
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-onetrade_dev}
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Admin (Development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: onetrade-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@onetrade.local
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  pgadmin_data:

networks:
  default:
    name: onetrade-network


